version: '3.4'

services:
  redis:
    image: redis:latest
    restart: always
  
  exchange-redis-service:
    image: exchange-redis-service
    build:
      context: ./redis-service
      dockerfile: ./redis-service/Dockerfile
    env_file:
      - .env
    depends_on:
      - redis
  
  exchange-telegram-bot:
    image: exchange-telegram-bot
    build:
      context: ./telegram-bot
      dockerfile: ./telegram-bot/Dockerfile
    env_file:
      - .env
    depends_on:
      - redis